/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package virtualpiano;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.sound.midi.MidiChannel;
import javax.sound.midi.MidiSystem;
import javax.sound.midi.Synthesizer;

/**
 *
 * @author 84946
 */
public class Piano extends javax.swing.JDialog implements KeyListener {

    /**
     * Creates new form Piano
     */
    Synthesizer synth;
    MidiChannel[] mc;
    int pitch;
    private String keys = "VGBHNMK,L.;/T6Y7UI9O0P-[";
    private boolean[] keyOn = new boolean[keys.length()];
    private boolean C,D,Dm,E,Em,F,G,A,Am,B;
    public Piano(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        addKeyListener(this);
        pitch = 0;
        try {
            synth = MidiSystem.getSynthesizer();
            synth.open();
            mc = synth.getChannels();
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    @Override
    public void keyTyped(KeyEvent e) {
//        System.out.println(e.toString());
    }

    @Override
    public void keyPressed(KeyEvent e) {
        int noteIndex = keys.indexOf((char) e.getKeyCode());
        if (noteIndex < 0 || keyOn[noteIndex]) {
            return;
        }
        keyOn[noteIndex] = true;
        mc[5].noteOn(noteIndex + 12 * 3 + pitch, 100);

    }

    @Override
    public void keyReleased(KeyEvent e) {
        int noteIndex = keys.indexOf((char) e.getKeyCode());
        if (noteIndex < 0) {
            return;
        }
        keyOn[noteIndex] = false;
        mc[5].noteOff(noteIndex + 12 * 3 + pitch, 100);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        F3t = new javax.swing.JButton();
        C3t = new javax.swing.JButton();
        C3 = new javax.swing.JButton();
        D3t = new javax.swing.JButton();
        E3 = new javax.swing.JButton();
        D3 = new javax.swing.JButton();
        G3t = new javax.swing.JButton();
        G3 = new javax.swing.JButton();
        F3 = new javax.swing.JButton();
        A3t = new javax.swing.JButton();
        A3 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        C4t = new javax.swing.JButton();
        G4t = new javax.swing.JButton();
        C4 = new javax.swing.JButton();
        D4t = new javax.swing.JButton();
        E4 = new javax.swing.JButton();
        D4 = new javax.swing.JButton();
        F4t = new javax.swing.JButton();
        F4 = new javax.swing.JButton();
        G4 = new javax.swing.JButton();
        A4t = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        C5t = new javax.swing.JButton();
        A4 = new javax.swing.JButton();
        C5 = new javax.swing.JButton();
        D5t = new javax.swing.JButton();
        E5 = new javax.swing.JButton();
        D5 = new javax.swing.JButton();
        G5t = new javax.swing.JButton();
        F5t = new javax.swing.JButton();
        G5 = new javax.swing.JButton();
        F5 = new javax.swing.JButton();
        A5t = new javax.swing.JButton();
        A5 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        C6t = new javax.swing.JButton();
        C6 = new javax.swing.JButton();
        D6t = new javax.swing.JButton();
        E6 = new javax.swing.JButton();
        D6 = new javax.swing.JButton();
        G6t = new javax.swing.JButton();
        F6t = new javax.swing.JButton();
        G6 = new javax.swing.JButton();
        F6 = new javax.swing.JButton();
        A6t = new javax.swing.JButton();
        A6 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        C7t = new javax.swing.JButton();
        C7 = new javax.swing.JButton();
        D7t = new javax.swing.JButton();
        E7 = new javax.swing.JButton();
        D7 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        F3t.setBackground(new java.awt.Color(0, 0, 0));
        F3t.setFocusPainted(false);
        F3t.setFocusable(false);
        F3t.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        F3t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F3tActionPerformed(evt);
            }
        });
        jPanel1.add(F3t, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 446, 36, 100));

        C3t.setBackground(new java.awt.Color(0, 0, 0));
        C3t.setFocusPainted(false);
        C3t.setFocusable(false);
        C3t.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        C3t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C3tActionPerformed(evt);
            }
        });
        jPanel1.add(C3t, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 446, 36, 100));

        C3.setText("C");
        C3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        C3.setDefaultCapable(false);
        C3.setDoubleBuffered(true);
        C3.setFocusPainted(false);
        C3.setFocusable(false);
        C3.setInheritsPopupMenu(true);
        C3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C3ActionPerformed(evt);
            }
        });
        jPanel1.add(C3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 446, 40, 160));

        D3t.setBackground(new java.awt.Color(0, 0, 0));
        D3t.setFocusPainted(false);
        D3t.setFocusable(false);
        D3t.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        D3t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D3tActionPerformed(evt);
            }
        });
        jPanel1.add(D3t, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 446, 36, 100));

        E3.setFocusPainted(false);
        E3.setFocusable(false);
        E3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        E3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E3ActionPerformed(evt);
            }
        });
        jPanel1.add(E3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 446, 40, 160));

        D3.setFocusPainted(false);
        D3.setFocusable(false);
        D3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        D3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        D3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D3ActionPerformed(evt);
            }
        });
        jPanel1.add(D3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 446, 40, 160));

        G3t.setBackground(new java.awt.Color(0, 0, 0));
        G3t.setFocusPainted(false);
        G3t.setFocusable(false);
        G3t.setInheritsPopupMenu(true);
        G3t.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        G3t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G3tActionPerformed(evt);
            }
        });
        jPanel1.add(G3t, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 446, 36, 100));

        G3.setFocusPainted(false);
        G3.setFocusable(false);
        G3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        G3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        G3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G3ActionPerformed(evt);
            }
        });
        jPanel1.add(G3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 446, 40, 160));

        F3.setFocusPainted(false);
        F3.setFocusable(false);
        F3.setRequestFocusEnabled(false);
        F3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        F3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F3ActionPerformed(evt);
            }
        });
        jPanel1.add(F3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 446, 40, 160));

        A3t.setBackground(new java.awt.Color(0, 0, 0));
        A3t.setFocusable(false);
        A3t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3tActionPerformed(evt);
            }
        });
        jPanel1.add(A3t, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 446, 36, 100));

        A3.setFocusable(false);
        A3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3ActionPerformed(evt);
            }
        });
        jPanel1.add(A3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 446, 40, 160));

        B3.setFocusable(false);
        B3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });
        jPanel1.add(B3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 446, 40, 160));

        C4t.setBackground(new java.awt.Color(0, 0, 0));
        C4t.setFocusPainted(false);
        C4t.setFocusable(false);
        C4t.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        C4t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C4tActionPerformed(evt);
            }
        });
        jPanel1.add(C4t, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 446, 36, 100));

        G4t.setBackground(new java.awt.Color(0, 0, 0));
        G4t.setFocusPainted(false);
        G4t.setFocusable(false);
        G4t.setInheritsPopupMenu(true);
        G4t.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        G4t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G4tActionPerformed(evt);
            }
        });
        jPanel1.add(G4t, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 446, 36, 100));

        C4.setText("C");
        C4.setDefaultCapable(false);
        C4.setFocusPainted(false);
        C4.setFocusable(false);
        C4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C4ActionPerformed(evt);
            }
        });
        jPanel1.add(C4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 446, 40, 160));

        D4t.setBackground(new java.awt.Color(0, 0, 0));
        D4t.setFocusPainted(false);
        D4t.setFocusable(false);
        D4t.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        D4t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D4tActionPerformed(evt);
            }
        });
        jPanel1.add(D4t, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 446, 36, 100));

        E4.setFocusPainted(false);
        E4.setFocusable(false);
        E4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        E4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E4ActionPerformed(evt);
            }
        });
        jPanel1.add(E4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 446, 40, 160));

        D4.setFocusPainted(false);
        D4.setFocusable(false);
        D4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        D4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        D4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D4ActionPerformed(evt);
            }
        });
        jPanel1.add(D4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 446, 40, 160));

        F4t.setBackground(new java.awt.Color(0, 0, 0));
        F4t.setFocusPainted(false);
        F4t.setFocusable(false);
        F4t.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        F4t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F4tActionPerformed(evt);
            }
        });
        jPanel1.add(F4t, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 446, 36, 100));

        F4.setFocusPainted(false);
        F4.setFocusable(false);
        F4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        F4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F4ActionPerformed(evt);
            }
        });
        jPanel1.add(F4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 446, 40, 160));

        G4.setFocusPainted(false);
        G4.setFocusable(false);
        G4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        G4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        G4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G4ActionPerformed(evt);
            }
        });
        jPanel1.add(G4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 446, 40, 160));

        A4t.setBackground(new java.awt.Color(0, 0, 0));
        A4t.setFocusable(false);
        A4t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A4tActionPerformed(evt);
            }
        });
        jPanel1.add(A4t, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 446, 36, 100));

        B4.setFocusable(false);
        B4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });
        jPanel1.add(B4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 446, 40, 160));

        C5t.setBackground(new java.awt.Color(0, 0, 0));
        C5t.setFocusPainted(false);
        C5t.setFocusable(false);
        C5t.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        C5t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C5tActionPerformed(evt);
            }
        });
        jPanel1.add(C5t, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 446, 36, 100));

        A4.setFocusable(false);
        A4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A4ActionPerformed(evt);
            }
        });
        jPanel1.add(A4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 446, 40, 160));

        C5.setText("C");
        C5.setDefaultCapable(false);
        C5.setFocusPainted(false);
        C5.setFocusable(false);
        C5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        C5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C5ActionPerformed(evt);
            }
        });
        jPanel1.add(C5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 446, 40, 160));

        D5t.setBackground(new java.awt.Color(0, 0, 0));
        D5t.setFocusPainted(false);
        D5t.setFocusable(false);
        D5t.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        D5t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D5tActionPerformed(evt);
            }
        });
        jPanel1.add(D5t, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 446, 36, 100));

        E5.setFocusPainted(false);
        E5.setFocusable(false);
        E5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        E5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E5ActionPerformed(evt);
            }
        });
        jPanel1.add(E5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 446, 40, 160));

        D5.setFocusPainted(false);
        D5.setFocusable(false);
        D5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        D5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        D5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D5ActionPerformed(evt);
            }
        });
        jPanel1.add(D5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 446, 40, 160));

        G5t.setBackground(new java.awt.Color(0, 0, 0));
        G5t.setFocusPainted(false);
        G5t.setFocusable(false);
        G5t.setInheritsPopupMenu(true);
        G5t.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        G5t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G5tActionPerformed(evt);
            }
        });
        jPanel1.add(G5t, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 446, 36, 100));

        F5t.setBackground(new java.awt.Color(0, 0, 0));
        F5t.setFocusPainted(false);
        F5t.setFocusable(false);
        F5t.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        F5t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F5tActionPerformed(evt);
            }
        });
        jPanel1.add(F5t, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 446, 36, 100));

        G5.setFocusPainted(false);
        G5.setFocusable(false);
        G5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        G5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        G5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G5ActionPerformed(evt);
            }
        });
        jPanel1.add(G5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 446, 40, 160));

        F5.setFocusPainted(false);
        F5.setFocusable(false);
        F5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        F5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F5ActionPerformed(evt);
            }
        });
        jPanel1.add(F5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 446, 40, 160));

        A5t.setBackground(new java.awt.Color(0, 0, 0));
        A5t.setFocusable(false);
        A5t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A5tActionPerformed(evt);
            }
        });
        jPanel1.add(A5t, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 446, 36, 100));

        A5.setFocusable(false);
        A5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A5ActionPerformed(evt);
            }
        });
        jPanel1.add(A5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 446, 40, 160));

        B5.setFocusable(false);
        B5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });
        jPanel1.add(B5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 446, 40, 160));

        C6t.setBackground(new java.awt.Color(0, 0, 0));
        C6t.setFocusPainted(false);
        C6t.setFocusable(false);
        C6t.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        C6t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C6tActionPerformed(evt);
            }
        });
        jPanel1.add(C6t, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 446, 36, 100));

        C6.setText("C");
        C6.setDefaultCapable(false);
        C6.setFocusPainted(false);
        C6.setFocusable(false);
        C6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        C6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C6ActionPerformed(evt);
            }
        });
        jPanel1.add(C6, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 446, 40, 160));

        D6t.setBackground(new java.awt.Color(0, 0, 0));
        D6t.setFocusPainted(false);
        D6t.setFocusable(false);
        D6t.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        D6t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D6tActionPerformed(evt);
            }
        });
        jPanel1.add(D6t, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 446, 36, 100));

        E6.setFocusPainted(false);
        E6.setFocusable(false);
        E6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        E6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E6ActionPerformed(evt);
            }
        });
        jPanel1.add(E6, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 446, 40, 160));

        D6.setFocusPainted(false);
        D6.setFocusable(false);
        D6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        D6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        D6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D6ActionPerformed(evt);
            }
        });
        jPanel1.add(D6, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 446, 40, 160));

        G6t.setBackground(new java.awt.Color(0, 0, 0));
        G6t.setFocusPainted(false);
        G6t.setFocusable(false);
        G6t.setInheritsPopupMenu(true);
        G6t.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        G6t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G6tActionPerformed(evt);
            }
        });
        jPanel1.add(G6t, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 446, 36, 100));

        F6t.setBackground(new java.awt.Color(0, 0, 0));
        F6t.setFocusPainted(false);
        F6t.setFocusable(false);
        F6t.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        F6t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F6tActionPerformed(evt);
            }
        });
        jPanel1.add(F6t, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 446, 36, 100));

        G6.setFocusPainted(false);
        G6.setFocusable(false);
        G6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        G6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        G6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G6ActionPerformed(evt);
            }
        });
        jPanel1.add(G6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 446, 40, 160));

        F6.setFocusPainted(false);
        F6.setFocusable(false);
        F6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        F6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F6ActionPerformed(evt);
            }
        });
        jPanel1.add(F6, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 446, 40, 160));

        A6t.setBackground(new java.awt.Color(0, 0, 0));
        A6t.setFocusable(false);
        A6t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A6tActionPerformed(evt);
            }
        });
        jPanel1.add(A6t, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 446, 36, 100));

        A6.setFocusable(false);
        A6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A6ActionPerformed(evt);
            }
        });
        jPanel1.add(A6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 446, 40, 160));

        B6.setFocusable(false);
        B6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });
        jPanel1.add(B6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 446, 40, 160));

        C7t.setBackground(new java.awt.Color(0, 0, 0));
        C7t.setFocusPainted(false);
        C7t.setFocusable(false);
        C7t.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        C7t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C7tActionPerformed(evt);
            }
        });
        jPanel1.add(C7t, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 446, 36, 100));

        C7.setText("C");
        C7.setDefaultCapable(false);
        C7.setFocusPainted(false);
        C7.setFocusable(false);
        C7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        C7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C7ActionPerformed(evt);
            }
        });
        jPanel1.add(C7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 446, 40, 160));

        D7t.setBackground(new java.awt.Color(0, 0, 0));
        D7t.setFocusPainted(false);
        D7t.setFocusable(false);
        D7t.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        D7t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D7tActionPerformed(evt);
            }
        });
        jPanel1.add(D7t, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 446, 36, 100));

        E7.setFocusPainted(false);
        E7.setFocusable(false);
        E7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        E7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E7ActionPerformed(evt);
            }
        });
        jPanel1.add(E7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 446, 40, 160));

        D7.setFocusPainted(false);
        D7.setFocusable(false);
        D7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        D7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        D7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D7ActionPerformed(evt);
            }
        });
        jPanel1.add(D7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 446, 40, 160));

        jButton19.setText("+");
        jButton19.setFocusable(false);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 70, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pitch : "+ pitch);
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setInheritsPopupMenu(false);
        jLabel1.setRequestFocusEnabled(false);
        jLabel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 70, 20));

        jButton18.setText("-");
        jButton18.setFocusable(false);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 70, 30));

        jButton2.setText("Em");
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 80, 80));

        jButton3.setText("B");
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 80, 80));

        jButton4.setText("D");
        jButton4.setFocusable(false);
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 80, 80));

        jButton5.setText("Dm");
        jButton5.setFocusable(false);
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 80, 80));

        jButton6.setText("E");
        jButton6.setFocusable(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 80, 80));

        jButton7.setText("C");
        jButton7.setFocusable(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 80, 80));

        jButton8.setText("F");
        jButton8.setFocusable(false);
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 80, 80));

        jButton9.setText("G");
        jButton9.setFocusable(false);
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 80, 80));

        jButton10.setText("A");
        jButton10.setFocusable(false);
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 80, 80));

        jButton11.setText("Am");
        jButton11.setFocusable(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 80, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void C3tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C3tActionPerformed
        mc[15].noteOn(37 + pitch, 100);
    }//GEN-LAST:event_C3tActionPerformed

    private void C3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C3ActionPerformed
        // TODO add your handling code here:
        mc[15].noteOn(36 + pitch, 100);
    }//GEN-LAST:event_C3ActionPerformed

    private void D3tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D3tActionPerformed
        mc[15].noteOn(39 + pitch, 100);
    }//GEN-LAST:event_D3tActionPerformed

    private void E3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E3ActionPerformed
        // TODO add your handling code here:
        mc[15].noteOn(40 + pitch, 100);
    }//GEN-LAST:event_E3ActionPerformed

    private void D3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D3ActionPerformed
        mc[15].noteOn(38 + pitch, 100);
    }//GEN-LAST:event_D3ActionPerformed

    private void G3tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G3tActionPerformed
        mc[15].noteOn(44 + pitch, 100);
    }//GEN-LAST:event_G3tActionPerformed

    private void F3tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F3tActionPerformed
        mc[15].noteOn(42 + pitch, 100);
    }//GEN-LAST:event_F3tActionPerformed

    private void G3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G3ActionPerformed
        mc[15].noteOn(43 + pitch, 100);
    }//GEN-LAST:event_G3ActionPerformed

    private void F3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F3ActionPerformed
        // TODO add your handling code here:
        mc[15].noteOn(41 + pitch, 100);
    }//GEN-LAST:event_F3ActionPerformed

    private void A3tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3tActionPerformed
        mc[15].noteOn(46 + pitch, 100);
    }//GEN-LAST:event_A3tActionPerformed

    private void A3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3ActionPerformed
        mc[15].noteOn(45 + pitch, 100);
    }//GEN-LAST:event_A3ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        mc[15].noteOn(47 + pitch, 100);
    }//GEN-LAST:event_B3ActionPerformed

    private void C4tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C4tActionPerformed
        mc[15].noteOn(49 + pitch, 100);
    }//GEN-LAST:event_C4tActionPerformed

    private void C4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C4ActionPerformed
        mc[15].noteOn(48 + pitch, 100);
    }//GEN-LAST:event_C4ActionPerformed

    private void D4tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D4tActionPerformed
        mc[15].noteOn(51 + pitch, 100);
    }//GEN-LAST:event_D4tActionPerformed

    private void E4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E4ActionPerformed
        mc[15].noteOn(52 + pitch, 100);
    }//GEN-LAST:event_E4ActionPerformed

    private void D4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D4ActionPerformed
        mc[15].noteOn(50 + pitch, 100);
    }//GEN-LAST:event_D4ActionPerformed

    private void G4tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G4tActionPerformed
        mc[15].noteOn(56 + pitch, 100);
    }//GEN-LAST:event_G4tActionPerformed

    private void F4tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F4tActionPerformed
        mc[15].noteOn(54 + pitch, 100);
    }//GEN-LAST:event_F4tActionPerformed

    private void G4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G4ActionPerformed
        mc[15].noteOn(55 + pitch, 100);
    }//GEN-LAST:event_G4ActionPerformed

    private void F4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F4ActionPerformed
        mc[15].noteOn(53 + pitch, 100);
    }//GEN-LAST:event_F4ActionPerformed

    private void A4tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A4tActionPerformed
        mc[15].noteOn(58 + pitch, 100);
    }//GEN-LAST:event_A4tActionPerformed

    private void A4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A4ActionPerformed
        mc[15].noteOn(57 + pitch, 100);
    }//GEN-LAST:event_A4ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        mc[15].noteOn(59 + pitch, 100);
    }//GEN-LAST:event_B4ActionPerformed

    private void C5tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C5tActionPerformed
        mc[15].noteOn(61 + pitch, 100);
    }//GEN-LAST:event_C5tActionPerformed

    private void C5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C5ActionPerformed
        mc[15].noteOn(60 + pitch, 100);
    }//GEN-LAST:event_C5ActionPerformed

    private void D5tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D5tActionPerformed
        mc[15].noteOn(63 + pitch, 100);
    }//GEN-LAST:event_D5tActionPerformed

    private void E5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E5ActionPerformed
        mc[15].noteOn(64 + pitch, 100);
    }//GEN-LAST:event_E5ActionPerformed

    private void D5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D5ActionPerformed
        mc[15].noteOn(62 + pitch, 100);
    }//GEN-LAST:event_D5ActionPerformed

    private void G5tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G5tActionPerformed
        mc[15].noteOn(68 + pitch, 100);
    }//GEN-LAST:event_G5tActionPerformed

    private void F5tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F5tActionPerformed
        mc[15].noteOn(66 + pitch, 100);
    }//GEN-LAST:event_F5tActionPerformed

    private void G5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G5ActionPerformed
        mc[15].noteOn(67 + pitch, 100);
    }//GEN-LAST:event_G5ActionPerformed

    private void F5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F5ActionPerformed
        mc[15].noteOn(65 + pitch, 100);
    }//GEN-LAST:event_F5ActionPerformed

    private void A5tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A5tActionPerformed
        mc[15].noteOn(70 + pitch, 100);
    }//GEN-LAST:event_A5tActionPerformed

    private void A5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A5ActionPerformed
        mc[15].noteOn(69 + pitch, 100);
    }//GEN-LAST:event_A5ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        mc[15].noteOn(71 + pitch, 100);
    }//GEN-LAST:event_B5ActionPerformed

    private void C6tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C6tActionPerformed
        mc[15].noteOn(73 + pitch, 100);
    }//GEN-LAST:event_C6tActionPerformed

    private void C6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C6ActionPerformed
        mc[15].noteOn(72 + pitch, 100);
    }//GEN-LAST:event_C6ActionPerformed

    private void D6tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D6tActionPerformed
        mc[15].noteOn(75 + pitch, 100);
    }//GEN-LAST:event_D6tActionPerformed

    private void E6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E6ActionPerformed
        mc[15].noteOn(76 + pitch, 100);
    }//GEN-LAST:event_E6ActionPerformed

    private void D6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D6ActionPerformed
        mc[15].noteOn(74 + pitch, 100);
    }//GEN-LAST:event_D6ActionPerformed

    private void G6tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G6tActionPerformed
        mc[15].noteOn(80 + pitch, 100);
    }//GEN-LAST:event_G6tActionPerformed

    private void F6tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F6tActionPerformed
        mc[15].noteOn(78 + pitch, 100);
    }//GEN-LAST:event_F6tActionPerformed

    private void G6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G6ActionPerformed
        mc[15].noteOn(79 + pitch, 100);
    }//GEN-LAST:event_G6ActionPerformed

    private void F6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F6ActionPerformed
        mc[15].noteOn(77 + pitch, 100);
    }//GEN-LAST:event_F6ActionPerformed

    private void A6tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A6tActionPerformed
        mc[15].noteOn(82 + pitch, 100);
    }//GEN-LAST:event_A6tActionPerformed

    private void A6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A6ActionPerformed
        mc[15].noteOn(81 + pitch, 100);
    }//GEN-LAST:event_A6ActionPerformed

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
        mc[15].noteOn(83 + pitch, 100);
    }//GEN-LAST:event_B6ActionPerformed

    private void C7tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C7tActionPerformed
        mc[15].noteOn(85 + pitch, 100);
    }//GEN-LAST:event_C7tActionPerformed

    private void C7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C7ActionPerformed
        mc[15].noteOn(84 + pitch, 100);
    }//GEN-LAST:event_C7ActionPerformed

    private void D7tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D7tActionPerformed
        mc[15].noteOn(87 + pitch, 100);
    }//GEN-LAST:event_D7tActionPerformed

    private void E7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E7ActionPerformed
        mc[15].noteOn(88 + pitch, 100);
    }//GEN-LAST:event_E7ActionPerformed

    private void D7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D7ActionPerformed
        mc[15].noteOn(86 + pitch, 100);
    }//GEN-LAST:event_D7ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        if (pitch <= 11) {
            pitch += 1;
        }
        jLabel1.setText("Pitch : " + pitch);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        if (pitch >= -11) {
            pitch -= 1;
        }
        jLabel1.setText("Pitch : " + pitch);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        mc[5].noteOn(36 + pitch, 100);
        mc[5].noteOn(40 + pitch, 100);
        mc[5].noteOn(43 + pitch, 100);
//        mc[5].noteOff(36 + pitch, 100);
//        mc[5].noteOff(40 + pitch, 100);
//        mc[5].noteOff(43 + pitch, 100);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Piano dialog = new Piano(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A3;
    private javax.swing.JButton A3t;
    private javax.swing.JButton A4;
    private javax.swing.JButton A4t;
    private javax.swing.JButton A5;
    private javax.swing.JButton A5t;
    private javax.swing.JButton A6;
    private javax.swing.JButton A6t;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton C3;
    private javax.swing.JButton C3t;
    private javax.swing.JButton C4;
    private javax.swing.JButton C4t;
    private javax.swing.JButton C5;
    private javax.swing.JButton C5t;
    private javax.swing.JButton C6;
    private javax.swing.JButton C6t;
    private javax.swing.JButton C7;
    private javax.swing.JButton C7t;
    private javax.swing.JButton D3;
    private javax.swing.JButton D3t;
    private javax.swing.JButton D4;
    private javax.swing.JButton D4t;
    private javax.swing.JButton D5;
    private javax.swing.JButton D5t;
    private javax.swing.JButton D6;
    private javax.swing.JButton D6t;
    private javax.swing.JButton D7;
    private javax.swing.JButton D7t;
    private javax.swing.JButton E3;
    private javax.swing.JButton E4;
    private javax.swing.JButton E5;
    private javax.swing.JButton E6;
    private javax.swing.JButton E7;
    private javax.swing.JButton F3;
    private javax.swing.JButton F3t;
    private javax.swing.JButton F4;
    private javax.swing.JButton F4t;
    private javax.swing.JButton F5;
    private javax.swing.JButton F5t;
    private javax.swing.JButton F6;
    private javax.swing.JButton F6t;
    private javax.swing.JButton G3;
    private javax.swing.JButton G3t;
    private javax.swing.JButton G4;
    private javax.swing.JButton G4t;
    private javax.swing.JButton G5;
    private javax.swing.JButton G5t;
    private javax.swing.JButton G6;
    private javax.swing.JButton G6t;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
